### PR TITLE
Patrick steveson - image upload with cloudinary

### PR DESCRIPTION
**Pull request by Mrsteveson**
# Description
Initialized our image uploader. Configured cloudinary settings as well as the multer middleware. Included an upload endpoint for testing the logic, this endpoint will be merged to be apart of the create a new post endpoint once that has finished being refactored to using steps.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [x] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [x] Test A, tested manually  on postman using a dummy photo

# Checklist

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Comment by Mrsteveson** [comment]
This PR is both completed and up for discussion because we are still intending to integrate the upload endpoint logic into our create a new post logic so that they can happen all at once when a user is creating a post. The currently included endpoint was implemented primarily to test the logic and make sure that the cloudinary account and our server were communicating properly.

**Comment by Mrsteveson** [comment]
Also, three new .env variables are needed for this endpoint to function. These are provided from cloudinary and are available at the cloudinary account dashboard page.
CLOUDINARY_CLOUD_NAME
CLOUDINARY_API_KEY
CLOUDINARY_API_SECRET

**Review by AJLambda — APPROVED** [review]
uploading images to endpoint is working w/ insomnia

**Review by KevinBrack — CHANGES_REQUESTED** [review]
Looks good. Thanks for the heads up about the new environment variables. This change requires a change to the documentation though. Please update the readme section about environment variables to reflect this. Above those 3 include a link to where anyone can sign up for those credentials. 

Keep up the great work! Message me when the documentation has been updated and I will merge this.

**Comment by Mrsteveson** [comment]
Updated the readme to include instructions on how to obtain your own cloud_name, api_key, and api_secret. As well as included those three variables into the .env section

**Review by KevinBrack — APPROVED** [review]
Perfect. Thanks.

**Pull request merged**
