### PR TITLE
Patrick steveson - including server and user automated tests

### PR DESCRIPTION
**Pull request by Mrsteveson**
# Description
Started to include automated testing for our endpoints, beginning with server and users.
Also edited the readme to include a missing endpoint and  dealt with duplicate endpoint section.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue) (maybe?)

## Change Status

- [x] Complete, tested, ready to review and merge

# How Has This Been Tested?

- [x] Test A ran tests locally using yarn test.
- [ ] Test B

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Comment by Mrsteveson** [comment]
The status code 200 test for the delete will work on the first run through if the testing db is seeded, but due to the foreign key restraint breaking the beforeEach truncate function it wont run back to back. Could use some looking at.

**Review by KevinBrack — COMMENTED** [review]
Please request a review from one of your peers soon. I think this PR is getting passed because it has a comment and might look done. Message me when this one is approved please.

**Review by AJLambda — APPROVED** [review]
tested locally with jest, all tests pass :+1:

**Review by matt-poloni — APPROVED** [review]
Tested locally and, once the setTimeout was added, the tests successfully ran.

**Pull request merged**
