### PR TITLE
Patrick steveson

### PR DESCRIPTION
**Pull request by Mrsteveson**
# Description
Begun to fill in and clean up the readme.
Backend has been initialized, dependencies installed and files structured.
Ready for deployment. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [ ] Complete, tested, ready to review and merge
- [x] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by Mrsteveson** [comment]
Thus far project has the basics required for deployment ready, once the github organization authorizes heroku access I will start the deployment.

All web development members as well as team lead have been invited to the heroku app.

**Review by AJLambda — APPROVED** [review]
I concur.

**Review by matt-poloni — APPROVED** [review]
Looks good to me

**Review by KevinBrack — APPROVED** [review]
Merging to master. Nice work!

**Pull request merged**
